config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # devise_scope :user do
  #   unauthenticated do
  #     root to: 'users/sessions#new', as: :unauthenticated_root
  #   end


  root to: 'users/custom_login_register_page#index', as: :root

  namespace :admin do
    resources :traders do
      get 'pendings', on: :collection
      post 'approve', on: :member
      get 'balance_new', on: :member
      post 'balance', on: :member
      get 'transactions', on: :collection
    end
  end

  resources :traders do
    member do
      get 'portfolio'
      get 'transaction'
      get 'balance_new'
      post 'balance'
      get 'buy_new'
      post 'buy'
      get 'sell_new'
      post 'sell'
    end
  end

  #this route is only for creating initial admin
  patch 'grant_admin', to: 'admin/traders#grant_admin', as: 'grant_admin'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

end

app/controllers/admin/traders_controller.rb
module Admin
    class TradersController < ApplicationController
        before_action :authorize_admin
        before_action :set_trader, only: [:show, :edit, :update, :balance_new, :balance]

        layout "admin_dashboard"
        # Get /admin/traders
        def index
            @traders = User.all.where(admin: false, approved: true)
            @pending_traders = User.where(admin: false, approved: false)
        end

        # GET /admin/traders/pendings
        def pendings
            @pending_traders = User.where(admin: false, approved: false)
        end

        #POST /admin/traders/:id/approve
        def approve
            @pending_trader = User.find(params[:id])
            @pending_trader.toggle!(:approved)

            #only triggers if user approved converted to true
            if @pending_trader.approved?
                TraderMailer.with(user: @pending_trader).approved_email.deliver_later
            end

            redirect_to admin_traders_path
        end

        # GET /admin/traders/:id/balance_new
        def balance_new
        end

        # POST /admin/traders/:id/balance
        def balance
            @trader.update(balance: (params[:initial_balance]))
            redirect_to admin_traders_path
        end

        # GET /admin/traders/transaction
        def transactions
            @transactions = Transaction.all.order(id: :desc)
        end

        #GET /admin/traders/:id
        def show
            @transactions = Transaction.where(user_id: @trader.id).order(id: :desc)
        end

        #GET /admin/traders/new
        def new
            @trader = User.new
        end

        #GET /admin/traders/:id/edit
        def edit
        end

        #POST /admin/traders
        def create
            @trader = User.new(trader_params)
            @trader.skip_confirmation!
            @trader.approved = true

            if @trader.save
                redirect_to admin_trader_path(@trader), notice: "Trader was successfully created."
                TraderMailer.with(user: @trader).approved_email.deliver_later
            else
                render :new, status: :unprocessable_entity
            end
        end

        #PATCH /admin/traders/:id
        def update
            if @trader.update(trader_params)
                redirect_to admin_trader_path(@trader), notice: "Trader was successfully updated."
            else
                render :edit, status: :unprocessable_entity
            end
        end

        # #temporaray method to grant admin status
        # def grant_admin
        #     current_user.update_attribute(:admin, true)
        #     redirect_to admin_traders_path, notice: "You have been granted admin status."
        # end

        private

        def authorize_admin
            redirect_to traders_path unless current_user.admin?
        end

        def set_trader
            @trader = User.find(params[:id])
        end

        def trader_params
            params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :approved)
        end
    end
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
    before_action :authorize_trader
    before_action :check_approval_status, only: [:buy_new, :buy, :sell_new, :sell, :balance, :balance_new]
    before_action :set_trader, only: [:index, :show, :edit, :update, :portfolio, :transaction, :buy_new, :sell_new, :balance_new]
    after_action :process_transaction, only: [:buy, :sell]
    helper_method :get_logo, :iex_client

    layout 'trader_dashboard'

    #GET /traders
    def index
        @quotes = iex_client.stock_market_list(:mostactive)
    end

    #GET traders/:symbol   ... :symbol value is the params[:id]
    def show
        @company = iex_client.company(params[:id])
        @logo = iex_client.logo(params[:id])
        @quote = iex_client.quote(params[:id])
        @chart_data = Stock.fetch_chart_data(iex_client, @company.symbol)
    end

    #GET /traders/:id/edit
    def edit
    end

    #PATCH traders/:id
    def update
      if @trader.update(trader_params)
          redirect_to admin_trader_path(@trader), notice: "Trader was successfully updated."
      else
          render :edit, status: :unprocessable_entity
      end
   end

    #GET traders/:id/portfolio
    def portfolio
      @stocks = current_user.stocks.where('shares > ?', 0).order(id: :desc)
    end

    #GET traders/:id/transaction
    def transaction
      @transactions = current_user.transactions.all.order(id: :desc)
    end

    #GET /traders/:symbol/buy_new  ... :symbol value is the params[:id]
    def buy_new
      @quote = iex_client.quote(params[:id])
    end

    #POST /traders/:id/buy
    def buy
      symbol, quantity, action, company_name = params.values_at(:symbol, :quantity, :action, :company_name)
      price = BigDecimal(iex_client.quote(symbol).latest_price.to_s)
      stock = Stock.create_or_update_stock(symbol, current_user, company_name)

      if (quantity.to_i * price) <= current_user.balance
        @transaction = Transaction.create_transaction(current_user, stock, quantity.to_i, price, action)
        @transaction.save!
        redirect_to portfolio_trader_path
      else
        flash[:alert] = 'Insufficient balance to make the purchase.'
        redirect_to buy_new_trader_path(symbol)
      end
    end

    #GET /traders/:symbol/sell_new  ... :symbol value is the params[:id]
    def sell_new
      @quote = iex_client.quote(params[:id])
      @company = iex_client.company(params[:id])
    end

    #POST /traders/:id/sell
    def sell
      symbol, quantity, action, price = params.values_at(:symbol, :quantity, :action, :price)
      price = price.to_i
      stock = Stock.find_by(symbol: symbol, user_id: current_user.id)

      if stock && stock.shares >= quantity.to_i
        @transaction = Transaction.create_transaction(current_user, stock, quantity.to_i, price, action)
        @transaction.save!
        redirect_to portfolio_trader_path
      else
        flash[:alert] = 'Insufficient quantity of shares to sell.'
        redirect_to sell_new_trader_path(symbol)
      end
    end

    #GET /traders/:id/balance_new
    def balance_new
      @balance = (params[:format])
    end

    #POST /traders/:id/balance
    def balance
      user = User.deposit(current_user, params[:init_balance].to_i)
      if user.persisted?
        flash[:notice] = 'Wallet balance has been successfully set.'
      else
        flash[:alert] = 'Failed to save the wallet balance.'
      end
      redirect_to portfolio_trader_path
    end

    private

    def authorize_trader
      redirect_to admin_traders_path unless !current_user.admin?
    end

    def set_trader
      @trader = current_user
    end

    def trader_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end

    def iex_client
      @iex_client ||= IEX::Api::Client.new
    end

    def get_logo(symbol)
      iex_client.logo(symbol).url
    end

    def process_transaction
      if !(@transaction.nil?)
        User.update_balance(@transaction.user, @transaction.action, @transaction.price * @transaction.quantity.to_i)
        if @transaction.action == 'buy'
          Stock.update_portfolio(@transaction.stock, @transaction.quantity, @transaction.price)
        else
          Stock.update_portfolio(@transaction.stock, -@transaction.quantity, @transaction.price)
        end
      else
        flash[:alert] = 'Failed Transaction.'
      end
    end

    def check_approval_status
      unless current_user.approved?
        flash[:alert] = 'You are not approved to perform this action.'
        redirect_to traders_path
      end
    end
  end

app/helpers/traders_helper.rb
module TradersHelper
end

app/views/traders/balance_new.html.erb
<main class="form-tag-container">
    <h2>Deposit</h2>

    <section class="stock-details">
      <div class="stock-data">
        <label>Current Balance</label> 
        <span>$<%=format_decimal_with_commas(@trader.balance)%></span>
      </div>
    </section>

    <div class="form-tag-box">
      <%= form_tag balance_trader_path(@trader) do %>
        <div class="input-box">      
          <%= text_field_tag :init_balance, nil, required: true %>
          <%= label_tag :init_balance, "Amount" %>
          <i class='bx bx-money'></i>
        </div>

        <%= submit_tag "Deposit", class: "form-btn deposit" %>
      <% end %>
    </div>
</main>

app/views/traders/buy_new.html.erb
<main class="form-tag-container">
  
  <section class="stock-details">
    <h4> Stock Details </h4>
    <div class="stock-data"> 
      <label>Company</label> 
      <span><%= @quote.company_name %></span> 
    </div>

    <div class="stock-data">
      <label>Current Price</label>
      <span>$<%= format_decimal_with_commas(@quote.latest_price) %></span> 
    </div>
  </section>

  <div class="form-tag-box">
    <%= form_with(url: buy_trader_path(@trader), method: :post) do |form| %>
      <%= form.hidden_field :symbol, value: @quote.symbol %>
      <%= form.hidden_field :action, value: 'buy' %>
      <%= form.hidden_field :company_name, value: @quote.company_name %>

      <div class="input-box">
        <%= form.number_field :quantity, min: 1, required: true %>
        <%= form.label :quantity %>
      </div>

      <div class="actions">
        <%= form.submit "Buy", class: "form-btn buy" %>
      </div>
    <% end %>
  </div>
</main>

app/views/traders/edit.html.erb
<%= link_to(portfolio_trader_path(@trader), class:"edit-return-btn") do %>
  <i class='bx bxs-chevrons-left'></i>
<% end %>

<div class="admin-edit-form">
  <h2>Edit Personal Details</h2>

  <div class="admin-form-box">
    <%= form_with(model: @trader, url: trader_path(@trader), method: :patch) do |form| %>
      <% if @trader.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@trader.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
            <% @trader.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="input-box">
        <%= form.text_field :first_name, autofocus: true, required: true %>
        <%= form.label :first_name %>
        <i class='bx bxs-user'></i>
      </div>

      <div class="input-box">
        <%= form.text_field :last_name, autofocus: true, required: true%>
        <%= form.label :last_name %>
        <i class='bx bxs-user'></i>
      </div>

      <div class="input-box">
        <%= form.text_field :email, autofocus: true, required: true %>
        <%= form.label :email %>
        <i class='bx bxs-envelope'></i>
      </div>

      <div class="logreg-link">
        <%# <%= form.submit %>
        <%= button_to "Update", new_registration_path(@trader), data: {turbo_frame: "_top"}, class: "form-btn animation" %>
      </div>
    <% end %>
  </div>

</div>

app/views/traders/index.html.erb
<% if !@trader.approved? %>
  <h3 class="non-approved-message">Your account verification is still in progress. We appreciate your patience as we ensure the security and integrity of our platform.</h3>
<% end %>

<div class="trader-assets-container">
    <span>
      <h2>Total Assets</h2>
      <p>$ <%= format_decimal_with_commas(@trader.balance + @trader.stocks.sum(:current_value)) %></p>
    </span>

    <% if @trader.approved? %>
      <%= link_to "Deposit", balance_new_trader_path(@trader), class:"deposit-btn" %>
    <% end %>
</div>

<table class="stock-list-table">
  <span class="table-title">Top-Performing Stocks</span>
  <thead>
    <tr class="stock-list">
      <th>Stocks</th>
      <th>Market Cap</th>
      <th>Price</th>
      <th>Change</th>
      <th>% Change</th>
      <% if @trader.approved? %>
        <th>Action</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
      <% if @quotes.nil? || @quotes.empty? %>
      <tr>
        <td colspan="8" style="text-align: center;">-- Data is currently unavailable. Please try again later. --</td>
      </tr>
      <% else %>
        <% @quotes.each do |quote| %>
          <tr class="table-data stock-list">

            <td>
              <%= link_to trader_path(quote.symbol), class:"table-stock-id" do %>
              <img class="company-logo" src="<%= get_logo(quote.symbol) %>" alt="Company Logo">
              <span class="stock-text-info">
                <div class="stock-symbol"><%= quote.symbol %></div>
                <div class="company-name"><%= quote.company_name %></div>
              </span>
              <% end %>
            </td>

            <td>
              <%= link_to trader_path(quote.symbol) do %>
                $<%= format_decimal_with_commas(quote.market_cap) %>
              <% end %>
            </td>

            <td>
              <%= link_to trader_path(quote.symbol) do %>
                $<%= format_decimal_with_commas(quote.latest_price) %>
              <% end %>
            </td>

            <td>
              <%= link_to trader_path(quote.symbol) do %>
                <%= quote.change %>
              <% end %>
            </td>

            <td>
              <%= link_to trader_path(quote.symbol) do %>
                <%= quote.change_percent %>
              <% end %>
            </td>

            <% if @trader.approved? %>
              <td>
                  <%= link_to "Buy", buy_new_trader_path(quote.symbol), class: "trader-buy-btn" %>
              </td>
            <% end %>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/traders/init_balance_new.html.erb
<h1>Initialize Balance</h1>
<p>Remember, you can only set your initial wallet balance once.
Be sure to set an adequate amount to maximize your usage with various stocks.</p>
<%= form_tag init_balance_path do %>
  <div class="form-group">
    <%= label_tag :initial_balance, "Initial Balance:" %>
    <%= text_field_tag :initial_balance %>
  </div>

  <%= submit_tag "Set Wallet Balance" %>
<% end %>

app/views/traders/portfolio.html.erb
<h1 class="portfolio-header">Portfolio</h1>

<main class="account-details-wrapper">
    <i class='bx bx-user account-photo' ></i>

    <span class="divider"></span>

    <section class="account-text-info">
        <h2><%= @trader.first_name %> <%= @trader.last_name %></h2>

        <p><%= @trader.email %></p>

      <% if @trader.approved %>
        <span class="verification-status verified"><i class='bx bxs-badge-check'></i>Verified</span>
      <% else %>
        <span class="verification-status unverified"><i class='bx bxs-checkbox-minus' ></i>Non-Verified</span>
      <% end %>
    </section>

    <%= link_to(edit_trader_path(@trader), class: "edit-btn") do %>
        <i class='bx bx-edit-alt' ></i>
    <% end %>

</main>

<div class="trader-assets-container">
    <span>
      <h2>Balance Remaining</h2>
      <p>$<%= format_decimal_with_commas(@trader.balance) %></p>
    </span>

    <span>
      <h2>Portfolio Value</h2>
      <p>$<%= format_decimal_with_commas(@stocks.sum(:current_value)) %></p>
    </span>

    <% if @trader.approved? %>
      <%= link_to "Deposit", balance_new_trader_path(@trader), class:"deposit-btn" %>
    <% end %>
</div>

<table>
  <thead>
    <tr class="portfolio-data">
      <th>Symbol</th>
      <th>Company Name</th>
      <th>Buying Price</th>
      <th>Current Price</th>
      <th>Shares</th>
      <th>Price Per Share</th>
      <th>Current Value</th>
      <% if @trader.approved? %>
        <th>Action</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @stocks.each do |stock| %>
      <tr class="table-data portfolio-data">

        <td>
           <%= link_to trader_path(stock.symbol) do %>
              <%= stock.symbol %>
           <% end %>
        </td>

        <td>
           <%= link_to trader_path(stock.symbol) do %>
              <%= stock.name %>
           <% end %>
        </td>

        <td>
          <%= link_to trader_path(stock.symbol) do %>
              $<%= format_decimal_with_commas(stock.price) %>
          <% end %>
        </td>

        <td>
          <%= link_to trader_path(stock.symbol) do %>
              <% #While the crontab is not working. %>
              $<%= format_decimal_with_commas(iex_client.quote(stock.symbol).latest_price) %>
          <% end %>
        </td>

        <td>
          <%= link_to trader_path(stock.symbol) do %>
              <%= stock.shares %>
          <% end %>
        </td>

        <td>
          <%= link_to trader_path(stock.symbol) do %>
              $<%= format_decimal_with_commas(stock.price_per_share) %>
          <% end %>
        </td>

        <td>
          <%= link_to trader_path(stock.symbol) do %>
              <% #While the crontab is not working. %>
              $<%= format_decimal_with_commas(
                (stock.shares * iex_client.quote(stock.symbol).latest_price).round(2)
                ) %>
          <% end %>
        </td>

        <% if @trader.approved? %>
          <td class="action-column">
              <%= link_to "Buy", buy_new_trader_path(stock.symbol), class: "portfolio-buy-btn" %>
              <%= link_to "Sell", sell_new_trader_path(stock.symbol), class: "portfolio-sell-btn" %>
          </td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/traders/sell_new.html.erb
<main class="form-tag-container">

  <section class="stock-details">
    <h4> Stock Details </h4>

    <div class="stock-data">
      <label>Company</label>
      <span><%= @quote.company_name %></span>
    </div>
    <div class="stock-data">
      <label>Shares Owned</label>
      <span><%= @trader.stocks.find_by(symbol: params[:id]).shares %></span>
    </div>
    <div class="stock-data">
      <label>Bought Price</label>
      <span>$<%= @trader.stocks.find_by(symbol: params[:id]).price %></span>
    </div>
    <div class="stock-data">
      <label>Current Price</label>
      <span>$<%= @quote.latest_price %></span>
    </div>
  </section>

  <div class="form-tag-box">
    <%= form_with( url: sell_trader_path(@trader), method: :post) do |form| %>
      <%= form.hidden_field :symbol, value: @quote.symbol %>
      <%= form.hidden_field :action, value: 'sell' %>
      <%= form.hidden_field :company_name, value: @quote.company_name %>
      <%= form.hidden_field :price, value: @quote.latest_price %>

      <div class="input-box">
        <%= form.number_field :quantity, min: 1, required: true %>
        <%= form.label :quantity %>
      </div>

      <div class="actions">
        <%= form.submit "Sell", class: "form-btn sell" %>
      </div>
    <% end %>
  </div>
</main>

app/views/traders/show.html.erb
<main class="trader-show-wrapper">
  <section class="stock-data-wrapper">
    <div class="stock-logo-name">
        <img src="<%= @logo.url %>" alt="Company Logo">
        <span>
          <div>
            <%= @company.company_name %>
          </div>
          <div>
            <%= @company.symbol %>
          </div>
        </span>
    </div>
    <div class="stock-latest-price">
       $<%= format_decimal_with_commas(@quote.latest_price) %>
       <span class="stock-price-change">
         <%= @quote.change %>%
       </span>
    </div>

    <div class="stock-data">
      <label>Market Cap</label>
      <span>$<%= format_decimal_with_commas(@quote.market_cap) %></span>
    </div>

    <div class="stock-data">
      <label>Percent Change</label>
      <span><%= @quote.change_percent %></span>
    </div>

    <div class="stock-data">
      <label>Website</label>
      <a href="<%= @company.website %>">
        <%= @company.website %>
      </a>
    </div>

    <div class="stock-data">
      <label>CEO</label>
      <span><%= @company.ceo %></span>
    </div>

    <div class="stock-data">
      <label>Industry</label>
      <span><%= @company.industry %></span>
    </div>

    <div class="stock-data">
      <label>Sector</label>
      <span><%= @company.sector %></span>
    </div>

    <% if @trader.approved? %>
      <div class="stock-data stock-btns">
          <%= link_to "Buy", buy_new_trader_path(@company.symbol), class: "buy btn" %>
          <% if @trader.stocks.exists?(symbol: @company.symbol) %>
            <%= link_to "Sell", sell_new_trader_path(@company.symbol), class: "sell btn" %>
          <% end %>
      </div>
    <% end %>

  </section>

  <section class="chart-wrapper">
    <%= candlestick_chart(
      @chart_data,
      class: 'chart-container',
      theme: 'roma',
      options:{
        color: "#fff",
        grid:{
          show: true,
        },
        xAxis: {
          axisTick: {
            alignWithLabel: true
          },
          min: "dataMin",
          max: "dataMax"
          },
        yAxis: {
          axisTick: {
            alignWithLabel: true
          },
          min: "dataMin",
          max: "dataMax"
        },
        dataZoom: [
      {
        type: 'slider',
        start: 0,
        end: 100,
        xAxisIndex: [0],
        zoomLock: false,
        throttle: 100,
        moveOnMouseMove: true,
        moveOnMouseWheel: true,
        preventDefaultMouseMove: true
      },
      {
        type: 'slider',
        start: 0,
        end: 100,
        yAxisIndex: [0],
        zoomLock: false,
        throttle: 100,
        moveOnMouseMove: true,
        moveOnMouseWheel: true,
        preventDefaultMouseMove: true
      },
      {
        type: 'inside',
        start: 0,
        end: 100,
        xAxisIndex: 0,
        zoomLock: false,
        throttle: 100,
        moveOnMouseMove: true,
        moveOnMouseWheel: true,
        preventDefaultMouseMove: true
      },
      {
        type: 'inside',
        start: 0,
        end: 100,
        yAxisIndex: 0,
        zoomLock: false,
        throttle: 100,
        moveOnMouseMove: true,
        moveOnMouseWheel: true,
        preventDefaultMouseMove: true
      },
    ],
      })
 %>
  </section>
</main>

app/views/traders/transaction.html.erb
<h1 class="transaction-page-header">Transactions History</h1>

<table>
  <thead>
    <tr class="transaction-history-data">
      <th>Date</th>
      <th>Time</th>
      <th>Symbol</th>
      <th>Name</th>
      <th>Action</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr class="table-data transaction-history-data">
        <td><%= transaction.created_at.to_date %></td>
        <td><%= transaction.created_at.strftime('%H:%M:%S') %></td>
        <td><%= transaction.stock.symbol %></td>
        <td><%= transaction.stock.name %></td>
        <td> 
          <span class="action <%= transaction.action == 'buy' ? "buy" : "sell"%>">
            <%= transaction.action %>
          </span>
        </td>
        <td><%= transaction.quantity %></td>
        <td>$<%= format_decimal_with_commas(transaction.price) %></td>
        <td>$<%= format_decimal_with_commas(transaction.total_amount) %></td>
      </tr>
    <% end %>
  </tbody>
</table>