config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # devise_scope :user do
  #   unauthenticated do
  #     root to: 'users/sessions#new', as: :unauthenticated_root
  #   end


  root to: 'users/custom_login_register_page#index', as: :root

  namespace :admin do
    resources :traders do
      get 'pendings', on: :collection
      post 'approve', on: :member
      get 'balance_new', on: :member
      post 'balance', on: :member
      get 'transactions', on: :collection
    end
  end

  resources :traders do
    member do
      get 'portfolio'
      get 'transaction'
      get 'balance_new'
      post 'balance'
      get 'buy_new'
      post 'buy'
      get 'sell_new'
      post 'sell'
    end
  end

  #this route is only for creating initial admin
  patch 'grant_admin', to: 'admin/traders#grant_admin', as: 'grant_admin'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

end

app/controllers/admin/traders_controller.rb
module Admin
    class TradersController < ApplicationController
        before_action :authorize_admin
        before_action :set_trader, only: [:show, :edit, :update, :balance_new, :balance]

        layout "admin_dashboard"
        # Get /admin/traders
        def index
            @traders = User.all.where(admin: false, approved: true)
            @pending_traders = User.where(admin: false, approved: false)
        end

        # GET /admin/traders/pendings
        def pendings
            @pending_traders = User.where(admin: false, approved: false)
        end

        #POST /admin/traders/:id/approve
        def approve
            @pending_trader = User.find(params[:id])
            @pending_trader.toggle!(:approved)

            #only triggers if user approved converted to true
            if @pending_trader.approved?
                TraderMailer.with(user: @pending_trader).approved_email.deliver_later
            end

            redirect_to admin_traders_path
        end

        # GET /admin/traders/:id/balance_new
        def balance_new
        end

        # POST /admin/traders/:id/balance
        def balance
            @trader.update(balance: (params[:initial_balance]))
            redirect_to admin_traders_path
        end

        # GET /admin/traders/transaction
        def transactions
            @transactions = Transaction.all.order(id: :desc)
        end

        #GET /admin/traders/:id
        def show
            @transactions = Transaction.where(user_id: @trader.id).order(id: :desc)
        end

        #GET /admin/traders/new
        def new
            @trader = User.new
        end

        #GET /admin/traders/:id/edit
        def edit
        end

        #POST /admin/traders
        def create
            @trader = User.new(trader_params)
            @trader.skip_confirmation!
            @trader.approved = true

            if @trader.save
                redirect_to admin_trader_path(@trader), notice: "Trader was successfully created."
                TraderMailer.with(user: @trader).approved_email.deliver_later
            else
                render :new, status: :unprocessable_entity
            end
        end

        #PATCH /admin/traders/:id
        def update
            if @trader.update(trader_params)
                redirect_to admin_trader_path(@trader), notice: "Trader was successfully updated."
            else
                render :edit, status: :unprocessable_entity
            end
        end

        # #temporaray method to grant admin status
        # def grant_admin
        #     current_user.update_attribute(:admin, true)
        #     redirect_to admin_traders_path, notice: "You have been granted admin status."
        # end

        private

        def authorize_admin
            redirect_to traders_path unless current_user.admin?
        end

        def set_trader
            @trader = User.find(params[:id])
        end

        def trader_params
            params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :approved)
        end
    end
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
    before_action :authorize_trader
    before_action :check_approval_status, only: [:buy_new, :buy, :sell_new, :sell, :balance, :balance_new]
    before_action :set_trader, only: [:index, :show, :edit, :update, :portfolio, :transaction, :buy_new, :sell_new, :balance_new]
    after_action :process_transaction, only: [:buy, :sell]
    helper_method :get_logo, :iex_client

    layout 'trader_dashboard'

    #GET /traders
    def index
        @quotes = iex_client.stock_market_list(:mostactive)
    end

    #GET traders/:symbol   ... :symbol value is the params[:id]
    def show
        @company = iex_client.company(params[:id])
        @logo = iex_client.logo(params[:id])
        @quote = iex_client.quote(params[:id])
        @chart_data = Stock.fetch_chart_data(iex_client, @company.symbol)
    end

    #GET /traders/:id/edit
    def edit
    end

    #PATCH traders/:id
    def update
      if @trader.update(trader_params)
          redirect_to admin_trader_path(@trader), notice: "Trader was successfully updated."
      else
          render :edit, status: :unprocessable_entity
      end
   end

    #GET traders/:id/portfolio
    def portfolio
      @stocks = current_user.stocks.where('shares > ?', 0).order(id: :desc)
    end

    #GET traders/:id/transaction
    def transaction
      @transactions = current_user.transactions.all.order(id: :desc)
    end

    #GET /traders/:symbol/buy_new  ... :symbol value is the params[:id]
    def buy_new
      @quote = iex_client.quote(params[:id])
    end

    #POST /traders/:id/buy
    def buy
      symbol, quantity, action, company_name = params.values_at(:symbol, :quantity, :action, :company_name)
      price = BigDecimal(iex_client.quote(symbol).latest_price.to_s)
      stock = Stock.create_or_update_stock(symbol, current_user, company_name)

      if (quantity.to_i * price) <= current_user.balance
        @transaction = Transaction.create_transaction(current_user, stock, quantity.to_i, price, action)
        @transaction.save!
        redirect_to portfolio_trader_path
      else
        flash[:alert] = 'Insufficient balance to make the purchase.'
        redirect_to buy_new_trader_path(symbol)
      end
    end

    #GET /traders/:symbol/sell_new  ... :symbol value is the params[:id]
    def sell_new
      @quote = iex_client.quote(params[:id])
      @company = iex_client.company(params[:id])
    end

    #POST /traders/:id/sell
    def sell
      symbol, quantity, action, price = params.values_at(:symbol, :quantity, :action, :price)
      price = price.to_i
      stock = Stock.find_by(symbol: symbol, user_id: current_user.id)

      if stock && stock.shares >= quantity.to_i
        @transaction = Transaction.create_transaction(current_user, stock, quantity.to_i, price, action)
        @transaction.save!
        redirect_to portfolio_trader_path
      else
        flash[:alert] = 'Insufficient quantity of shares to sell.'
        redirect_to sell_new_trader_path(symbol)
      end
    end

    #GET /traders/:id/balance_new
    def balance_new
      @balance = (params[:format])
    end

    #POST /traders/:id/balance
    def balance
      user = User.deposit(current_user, params[:init_balance].to_i)
      if user.persisted?
        flash[:notice] = 'Wallet balance has been successfully set.'
      else
        flash[:alert] = 'Failed to save the wallet balance.'
      end
      redirect_to portfolio_trader_path
    end

    private

    def authorize_trader
      redirect_to admin_traders_path unless !current_user.admin?
    end

    def set_trader
      @trader = current_user
    end

    def trader_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end

    def iex_client
      @iex_client ||= IEX::Api::Client.new
    end

    def get_logo(symbol)
      iex_client.logo(symbol).url
    end

    def process_transaction
      if !(@transaction.nil?)
        User.update_balance(@transaction.user, @transaction.action, @transaction.price * @transaction.quantity.to_i)
        if @transaction.action == 'buy'
          Stock.update_portfolio(@transaction.stock, @transaction.quantity, @transaction.price)
        else
          Stock.update_portfolio(@transaction.stock, -@transaction.quantity, @transaction.price)
        end
      else
        flash[:alert] = 'Failed Transaction.'
      end
    end

    def check_approval_status
      unless current_user.approved?
        flash[:alert] = 'You are not approved to perform this action.'
        redirect_to traders_path
      end
    end
  end

app/helpers/traders_helper.rb
module TradersHelper
end

app/views/admin/traders/balance_new.html.erb
<main class="form-tag-container">
  <h2>Initialize Balance for Trader</h2>

  <section class="stock-details trader-details">
    <div class="stock-data">
      <label>Trader</label> 
      <span><%= @trader.first_name %> <%= @trader.last_name %><span>
    </div>
  </section>

  <div class="form-tag-box">
    <%= form_with(url: balance_admin_trader_path(@trader), method: :post) do |form| %>
      <div class="input-box">
        <%= form.text_field :initial_balance, required: true %>
        <%= form.label :initial_balance, "Amount" %>
        <i class='bx bx-money'></i>
      </div>

      <%= form.submit "Set Balance", class: "form-btn deposit"  %>
    <% end %>
  </div>
</main>

app/views/admin/traders/edit.html.erb
<%= link_to(admin_trader_path(@trader), class:"edit-return-btn") do %>
  <i class='bx bxs-chevrons-left'></i>
<% end %>

<div class="admin-edit-form">
  <h2>Edit Trader Details</h2>

  <div class="admin-form-box">
    <%= form_with(model: @trader, url: admin_trader_path(@trader), method: :patch) do |form| %>
      <% if @trader.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@trader.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
            <% @trader.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="input-box">
        <%= form.text_field :first_name, autofocus: true, required: true %>
        <%= form.label :first_name %>
        <i class='bx bxs-user'></i>
      </div>

      <div class="input-box">
        <%= form.text_field :last_name, autofocus: true, required: true%>
        <%= form.label :last_name %>
        <i class='bx bxs-user'></i>
      </div>

      <div class="input-box">
        <%= form.text_field :email, autofocus: true, required: true %>
        <%= form.label :email %>
        <i class='bx bxs-envelope'></i>
      </div>

      <div class="logreg-link">
        <%# <%= form.submit %>
        <%= button_to "Update", new_registration_path(@trader), data: {turbo_frame: "_top"}, class: "form-btn animation" %>
      </div>
    <% end %>
  </div>

</div>

app/views/admin/traders/index.html.erb
<section class="pending-traders-wrapper">
  <header class="list-header">
    <h2>Pending Accounts</h2>
    <span><%= @pending_traders.length %></span>
    <i id="pending-toggle-list" class='bx bx-expand-vertical'></i>
  </header>

  <ul class="pending-traders-list">
    <% @pending_traders.each do |trader| %>
      <li class="trader">
        <span><%= trader.id %></span>
        <span><%= trader.first_name%> <%= trader.last_name%></span>
        <span><%= trader.email %></span>
        <%= button_to "Approve account", approve_admin_trader_path(trader), method: :post, class: "approve-btn" %>
      </li>
    <% end %>
  </ul>
</section>

<section class="approved-traders-wrapper">
  <header class="list-header">
      <h2>Trader Accounts</h2>
      <span><%= @traders.length %></span>
      <i id="approved-toggle-list" class='bx bx-expand-vertical'></i>
  </header>
  <div class="trader approved-list-header">
    <span>Account ID</span>
    <span>Name</span>
    <span>Email</span>
    <span>Balance</span>
    <span>Buttons</span>
  </div>

  <ul class="approved-traders-list">
    <% @traders.each do |trader| %>
      <li class="trader trader-data">
        <%= link_to(admin_trader_path(trader), class: "approved-trader-link") do %>
          <span><%= trader.id %></span>
          <span><%= trader.first_name%> <%= trader.last_name%></span>
          <span><%= trader.email %></span>
          <span><%= trader.balance %></span>
          <div class="trader-btns-wrapper">
            <%= link_to "Set Balance", balance_new_admin_trader_path(trader), class: "balance-btn" %>
            <%= button_to "Revoke account", approve_admin_trader_path(trader), method: :post, class: "revoke-btn" %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

<%# this method is only for creating initial admin %>
<%# <%= button_to "Grant Admin", grant_admin_path, method: :patch, data: { confirm: "Are you sure you want to grant admin status to this user?" } %>

app/views/admin/traders/new.html.erb
<div class="admin-form-container">
  <h2>Create an account</h2>

  <div class="admin-form-box">
    <%= form_for(@trader, url: admin_traders_path(@trader), method: :post) do |f| %>

      <div class="input-box">
        <%= f.text_field :email, autofocus: true, autocomplete: "email", required: true %>
        <%= f.label :email %>
        <i class='bx bxs-envelope'></i>
      </div>

      <div class="input-box">
        <%= f.text_field :first_name, autofocus: true, required: true %>
        <%= f.label :first_name %>
        <i class='bx bxs-user'></i>
      </div>

      <div class="input-box">
        <%= f.text_field :last_name, autofocus: true, required: true %>
        <%= f.label :last_name %>
        <i class='bx bxs-user'></i>
      </div>

      <div class="input-box">
        <%= f.password_field :password, autocomplete: "new-password", required: true %>
        <%= f.label :password %>
        <i class='bx bxs-lock-alt'></i>
      </div>

      <div class="input-box">
        <%= f.password_field :password_confirmation, autocomplete: "new-password", required: true %>
        <%= f.label :password_confirmation %>
        <i class='bx bxs-lock-alt'></i>
      </div>

      <div class="logreg-link">
        <%# <%= f.submit "Sign up", class: "form-btn" %>
        <%= button_to "Sign up", new_registration_path(@trader), data: {turbo_frame: "_top"}, class: "form-btn animation" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/traders/show.html.erb
<h1 class="page-header">Account Details</h1>

<main class="account-details-wrapper">
    <i class='bx bx-user account-photo' ></i>

    <span class="divider"></span>
    
    <section class="account-text-info">
        <h2><%= @trader.first_name %> <%= @trader.last_name %></h2>

        <p><%= @trader.email %></p>

        <p>Balance: <%= @trader.balance %> USD</p>
    </section>

    <%= link_to(edit_admin_trader_path(@trader), class: "edit-btn") do %>
        <i class='bx bx-edit-alt' ></i>
    <% end %>

</main>

<section class="transaction-list-wrapper">
    <header class="transaction-list-headers">
        <span>Stock Symbol</span>
        <span>Stock Name</span>
        <span>Action</span>
        <span>Quantity</span>
        <span>Price(USD)</span>
        <span>Total Amount(USD)</span>
        <span>Date</span>
        <span>Time</span>
    </header>

    <ul class="transactions-list">
        <% @transactions.each do |transaction| %>
            <li class="transaction">
                <span><%= transaction.stock.symbol %></span>
                <span><%= transaction.stock.name %></span>
                <span class="<%= transaction.action == 'buy' ? 'buy' : 'sell' %>">
                        <%= transaction.action %>
                </span>
                <span><%= transaction.quantity %></span>
                <span><%= transaction.price %></span>
                <span><%= transaction.total_amount %></span>
                <span><%= transaction.created_at.to_date %></span>
                <span><%= transaction.created_at.strftime('%H:%M:%S') %></span>
            </li>
        <% end %>
    </ul>
</section>

app/views/admin/traders/transaction.html.erb
<h1>All Transactions</h1>

<table border="1">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Account Name</th>
      <th>Symbol</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Action</th>
      <th>Total Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.created_at.to_date %></td>
        <td><%= transaction.created_at.strftime('%H:%M:%S') %></td>
        <td><%= transaction.user.first_name %> <%= transaction.user.last_name %></td>
        <td><%= transaction.stock.symbol %></td>
        <td><%= transaction.stock.name %></td>
        <td><%= transaction.quantity %></td>
        <td>$<%= transaction.price %></td>
        <td><%= transaction.action %></td>
        <td>$<%= transaction.total_amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/traders/transactions.html.erb
<h1 class="transactions-page-header">All Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Account Name</th>
      <th>Symbol</th>
      <th>Stock Name</th>
      <th>Action</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total Amount</th>
      <th>Date</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr class="table-data">
        <td><%= transaction.user.first_name %> <%= transaction.user.last_name %></td>
        <td><%= transaction.stock.symbol %></td>
        <td><%= transaction.stock.name %></td>
        <td>
          <span class="<%= transaction.action == 'buy' ? 'buy' : 'sell' %>">
            <%= transaction.action %>
          </span>
        </td>
        <td><%= transaction.quantity %></td>
        <td>$<%= transaction.price %></td>
        <td>$<%= transaction.total_amount %></td>
        <td><%= transaction.created_at.to_date %></td>
        <td><%= transaction.created_at.strftime('%H:%M:%S') %></td>
      </tr>
    <% end %>
  </tbody>
</table>