config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  # devise_scope :user do
  #   unauthenticated do
  #     root to: 'users/sessions#new', as: :unauthenticated_root
  #   end


  root to: 'users/custom_login_register_page#index', as: :root

  namespace :admin do
    resources :traders do
      get 'pendings', on: :collection
      post 'approve', on: :member
      get 'balance_new', on: :member
      post 'balance', on: :member
      get 'transactions', on: :collection
    end
  end

  resources :traders do
    member do
      get 'portfolio'
      get 'transaction'
      get 'balance_new'
      post 'balance'
      get 'buy_new'
      post 'buy'
      get 'sell_new'
      post 'sell'
    end
  end

  #this route is only for creating initial admin
  patch 'grant_admin', to: 'admin/traders#grant_admin', as: 'grant_admin'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

end

app/views/layouts/admin_dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>StockPulse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css'%>
    <%= javascript_include_tag 'dashboard', 'data-turbo-track': 'reload', defer: true %>
    <%= javascript_include_tag 'admin_index', 'data-turbo-track': 'reload', defer: true %>

  </head>

  <body class="admin-body">
    
    <header class="admin-header">
        <div class="logo">
            <i class='bx bx-candles' ></i><span>StockPulse</span>
        </div>

        <div class="admin-header-input">
            <input type="text">
            <i class='bx bx-search' ></i>
        </div>

        <i class='bx bx-user'></i>
    </header>

    <section class="admin-dashboard">
        <div class="admin-navbar">
            <div class="admin-navbar-routes">
                <div id="toggle-width-btn" class="nav-item">
                    <i class='bx bx-expand-horizontal'></i><span class="nav-item-text">Minimize</span>
                </div>

                <%= link_to(admin_traders_path, class: "nav-item") do %>
                    <i class='bx bx-home'></i><span class="nav-item-text">Home</span>
                <% end %>
                
                <%=link_to(transactions_admin_traders_path, class: "nav-item") do %>
                    <i class='bx bx-wallet'></i><span class="nav-item-text">Transactions</span>
                <% end %>
                
                <%= link_to(new_admin_trader_path, class: "nav-item") do %>
                    <i class='bx bx-user-plus'></i><span class="nav-item-text">Create account</span>
                <% end %>
            </div>

            <div class="admin-account-btns">   
                <%= button_to(destroy_user_session_path, method: :delete, class: "nav-item logout-btn") do %>
                    <i class='bx bx-power-off'></i><span class="nav-item-text">Logout</span>
                <% end %>
            </div>
        </div>

        <main class="admin-content">
            <%= yield %>
        </main>
    </section>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>StockPulse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css'%>
    <%= javascript_include_tag 'custom_login_register_page', 'data-turbo-track': 'reload', defer: true %>

  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/layouts/trader_dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>StockPulse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css'%>
    <%= javascript_include_tag 'dashboard', 'data-turbo-track': 'reload', defer: true %>

  </head>

  <body class="admin-body">
    
    <header class="admin-header">
        <div class="logo">
            <i class='bx bx-candles' ></i><span>StockPulse</span>
        </div>

        <div class="admin-header-input">
            <input type="text">
            <i class='bx bx-search' ></i>
        </div>

        <i class='bx bx-user'></i>
    </header>

    <section class="admin-dashboard">
        <div class="admin-navbar">
            <div class="admin-navbar-routes">
                <div id="toggle-width-btn" class="nav-item">
                    <i class='bx bx-expand-horizontal'></i><span class="nav-item-text">Minimize</span>
                </div>

                <%= link_to(traders_path, class: "nav-item") do %>
                    <i class='bx bx-home'></i><span class="nav-item-text">Home</span>
                <% end %>
                
                <%=link_to(portfolio_trader_path(@trader), class: "nav-item") do %>
                    <i class='bx bx-wallet'></i><span class="nav-item-text">Portfolio</span>
                <% end %>
                
                <%= link_to(transaction_trader_path(@trader), class: "nav-item") do %>
                    <i class='bx bx-history'></i><span class="nav-item-text">Transaction History</span>
                <% end %>
            </div>

            <div class="admin-account-btns">   
                <%= button_to(destroy_user_session_path, method: :delete, class: "nav-item logout-btn") do %>
                    <i class='bx bx-power-off'></i><span class="nav-item-text">Logout</span>
                <% end %>
            </div>
        </div>

        <main class="admin-content">
            <%= yield %>
        </main>
    </section>
  </body>

</html>